### ISSUE TITLE
Could not find nokogiri (1.11.4) in any sources

### ISSUE THREAD

**Issue by tommeier** [github/licensed#362] opened 2021-05-18 21:37 UTC
```
  * Errors:
    * native.bundler.nokogiri
      - could not find nokogiri (1.11.4) in any sources
```

on: `v3.0.1`

Is working with same Gemfile on `2.14.4`

**Comment by jonabc** [comment] 2021-05-18 21:41
@tommeier :wave: can you provide a repro project or gemfile so I can take a better look at whats going on? 🙇   The bundler source went through some significant changes 2.x.x -> 3.x.x so I'm not terribly surprised to see some things like this pop up

**Comment by tommeier** [comment] 2021-05-19 10:09
hi @jonabc ,

Well - I'd love too... 😆  I'm just for some reason unable too. Completely baffled.

In our (albeit gigantic monolith) project, I get this every time with the root `Gemfile` simplified down to this:

```
source "https://rubygems.org"

group :development do
  gem "licensed", group: :development
end
gem 'appium_lib'
```

WIth the most simple `.licensed.yml` of:

```
cache_path: license_cache

sources:
  bundler: true
```

However, on a clean seperate project (same bundler `2.2.11` and same ruby `2.7.2`) this issue doesn't exist.

On our project root:

```
Caching dependency records for up
  bundler
    Using appium_lib (11.2.0)
    Using appium_lib_core (4.5.0)
    Using childprocess (3.0.0)
    Using eventmachine (1.2.7)
    Using faye-websocket (0.11.0)
    Using rubyzip (2.3.0)
    Using selenium-webdriver (3.142.7)
    Using tomlrb (1.3.0)
    Using websocket-driver (0.7.3)
    Using websocket-extensions (0.1.5)

  * Errors:
    * up.bundler.nokogiri
      - could not find nokogiri (1.11.4) in any sources
```

On a clean repo with the same gemfile + licensed.yml:

```
Caching dependency records for test-bundle
  bundler
    Using appium_lib (11.2.0)
    Using appium_lib_core (4.5.0)
    Using childprocess (3.0.0)
    Using eventmachine (1.2.7)
    Using faye-websocket (0.11.0)
    Using nokogiri (1.11.4)
    Using racc (1.5.2)
    Using rubyzip (2.3.0)
    Using selenium-webdriver (3.142.7)
    Using tomlrb (1.3.0)
    Using websocket-driver (0.7.3)
    Using websocket-extensions (0.1.5)
  * 12 bundler dependencies
```


I have absolutely no idea why, however I've proven its PEBKAC somewhere in our monolith, somehow  - will keep looking 👓

**Comment by jonabc** [comment] 2021-05-19 14:41
For the "keep looking" aspect, is there any custom configuration to either ruby or bundler in the original project?  Please do feel free to reopen this if you find out what's going on and there's something to fix in this project 🙇

**Comment by bblimke** [comment] 2021-06-25 07:25
@tommeier have you found what was causing the problem and fix for it? I'm experiencing the same in our project.

**Comment by bblimke** [comment] 2021-06-25 07:28
Just found that after upgrading bundler from version 2.2.15 to version 2.2.21 the problem is gone.

**Comment by tommeier** [comment] 2021-08-23 05:42
@bblimke alas I never did, we don't appear to be doing anything fancy, not with ruby, bundler v2.2.26 the issue remains for our `source_path` elements

**Comment by jonabc** [comment] 2021-08-23 15:04
@tommeier :wave: do you mean to say that you're still having issues here and the bug hasn't been resolved for you?

A few followup questions
- how are you running licensed in the failing environment
- what version of licensed are you using
- is there any stored bundler configuration in the failing environmnet

Generally, I've found that the "could not find * in any sources" for bundler gems that build native dependencies (like nokogiri) comes from running licensed in a different OS type than was used for bundler to install dependencies.  As an example, you might see this if you're running `bundle install` directly on a host but running `licensed verify` from a docker container.

**Comment by tommeier** [comment] 2021-08-24 03:43
@jonabc 👋 unfortunately yet, spotted the update on latest bundler and unfortunately, weirdly same issue.

  * Simply running `bundle exec licenced cache`
  * Licensed: `3.2.0` , `Bundler version 2.2.26`, Ruby `2.7.4`
  * We have 2 bundle configs: 

```
Settings are listed in order of priority. The top value will be used.
build.thin
Set for the current user (/Users/tommeier/.bundle/config): "--with-cflags=-Wno-error=implicit-function-declaration"

gems.graphql.pro
Set for the current user (/Users/tommeier/.bundle/config): "[REDACTED]:[REDACTED]"
```

**Comment by jonabc** [comment] 2021-08-25 00:39
@tommeier I'm going to reopen this since you're still seeing the problem.  I misread your earlier comment and thought the problem was resolved in your project.

Some more questions for the environment setup
- is licensed listed in your gemfile and installed via `bundle install`?
- can you include here the `gem nokogiri` reference in your gemfile if you're explicitly specifying it?
- there should be a non-nested reference to nokogiri in your lockfile - can you verify it specifies 1.11.4?
- when you look at your bundler install location, do you have either of the following paths?
   - `gems/ruby/2.7.0/gems/nokogiri-1.11.4-x86_64-darwin` (or if similar but not exact, what path do you see?)
   - `gems/ruby/2.7.0/extensions/nokogiri-1.11.4` (or if similar but not exact, what path do you see?)

**Comment by tommeier** [comment] 2021-08-31 01:35
@jonabc will email you the deets!

**Comment by jonabc** [comment] 2021-09-03 21:56
@tommeier thanks for the reproduction details 🙇 . I was able to reproduce the issue, but it was an unexpected challenge to do so 😂 !

I'm still trying to figure out exactly what's going on or how to fix it, but I was able to make the failure happen for the native subproject by installing everything, changing the platform in Gemfile.lock `bundle lock --add-platform ruby && bundle lock --remove-platform x86_64-darwin-19`, re-running `bundle install` and then `bundle exec licensed list` from the root.  I might have had a `bundle install --redownload` in there at some point too to make sure everything was in there as expected.

I'm looking into a fix on the licensed side of things, hopefully it won't be anything too complicated.  I'm not entirely sure of a workaround at the moment though you could use on your side

**Comment by jonabc** [comment] 2021-09-04 04:16
:wave: I opened https://github.com/github/licensed/pull/392 as a fix, which I verified fixed the problem on my local reproduction ☝️ .  I'm going to let that sit for a few days and review it with fresh eyes because the interaction of the source enumerator with bundler's internal object model has been a love/hate relationship over the years and I'm just a bit wary 😆 

Anyway, at least the problem has been identified now and has a potential solution 👍 .  Thanks for all your help in tracking this down.

**Comment by tommeier** [comment] 2021-09-05 04:43
brilliant! thanks @jonabc - will test tomorrow morning!

**Comment by tommeier** [comment] 2021-09-06 02:29
confirmed! Works perfectly with no issues - thank you!! 👏

**Closed** 2021-09-06 17:38 UTC

**Comment by jonabc** [comment] 2021-09-06 18:09
Licensed 3.2.1 is released that includes this fix

**Comment by elct9620** [comment] 2021-09-07 15:28
Hi, all

I have the same problem, but our daily CI build failed after licensed upgraded to 3.2.1.
After clear the cache, both 3.2.0 and 3.2.1 are unable to correctly run `licensed cache` for now, only 20% of gems can correctly be found. 😅
