### ISSUE TITLE
Ignored go modules seems not to work if there is a strings package

### ISSUE THREAD

**Issue by andreas-hakansson-ingka** [github/licensed#409] opened 2021-09-24 08:33 UTC
Hi

We recently updated one of our internal Go modules, let's call it `foo-go-bar` where we added an internal package `strings` in the `internal` path. After we did that, our license checks started to fail in one of our projects that had a dependency on this module.

```bash
Errors:
* foo.go.github.com/acme/foo-go-bar/internal/strings
  filename: acme.licenses/go/github.com/acme/foo-go-bar/internal/strings.dep.yml, version: v1.9.0, license: none, allowed: false
    - missing license text
    - license needs review: none
```

We have added our internal modules to the ignore list, and it worked up until the point when we added `internal/strings` to `foo-go-bar`

```yaml
ignored:
  go:
    - github.com/acme/foo-go-*
```

It seems that the ignore has no effect for `foo-go-bar/internal/strings.dep.yml` but it does work fine for `foo-goo-bar`. It doesn't either help if I add the full path `github.com/acme/foo-go-bar/internal/strings` to the ignore list

We did try with 3.3.0 and the problem remains

PS. I can't say for sure that this is restricted to a `strings` package.. but we've not had issues before with packages that has a lot of internal packages

**Comment by jonabc** [comment] 2021-09-24 15:02
@andreas-hakansson-ingka these patterns are glob-based and have [FNM_PATHNAME](https://ruby-doc.org/core-3.0.2/File/Constants.html) set for path matching.  The `*` wildcard will not match path separators, while `**` will.  There is a bit more information in the [docs for the go source](https://github.com/github/licensed/blob/master/docs/sources/go.md#reviewing-and-ignoring-all-packages-from-a-go-module)

I think what you'd need here is a combination of
```yml
ignored:
  go:
    - github.com/acme/foo-go-bar
    - github.com/acme/foo-go-bar/**/*
```

Closing this for now, please reopen if this doesn't resolve your issue

**Closed by jonabc** 2021-09-24 15:02 UTC

**Comment by andreas-hakansson-ingka** [comment] 2021-09-26 11:32
@jonabc hmm that might be it, but I still can't seem to quite make it work. The private modules, that I'd like to ignore, all follow a naming convention of `foo-go-*` (like `foo-go-something` and `foo-go-different). And many of them have internal packages like `internal/strings`, `internal/metrics`, and so on. What I need is a pattern that matches all of those packages and their internal packages.

However, it doesn't seem like `- github.com/acme/foo-go-*/**/*` does the trick either.. in fact it starts to pick up more (12 in total) of our own packages if we change it to this. I'll be the first to point out that it is very likely due to my poor understanding of the pattern syntax for `File.fnmatch` 😄

**Comment by jonabc** [comment] 2021-09-27 16:53
@andreas-hakansson-ingka `github.com/acme/foo-go-*/**/*` as you mentioned will match quite a lot 😅 .  Opting for multiple patterns is usually easier than trying to make a single pattern work for all cases.

What types of package paths are being picked up that shouldn't be?  Is there a reason you need to report on any internal packages in the first place or is it 👍  to ignore all of the packages from your company/org rather than just your team?  Usually, licensing guidance I've seen is to report on 3rd party dependencies only

**Comment by andreas-hakansson-ingka** [comment] 2021-09-27 18:38
@jonabc Our organization `acme` is shared by many teams (mono-organization). Our team repos all follow the naming convention `foo-go-*`. We want to _exclude_ our (my teams) own repos from scanning, but not repos (which we might end up having a module dependency down the road) that belong to other team (we don't implicitly apply trust because it's in the same organization, right now). We do want to scan any module that is not ours (`foo-go-*)

We've previously done this using `github.com/acme/foo-go-*` which worked great, until the other day when one of our modules had an internal package `internal/strings` added. All of a sudden that sub-package was being picked up

Example module

```
foo-go-awesome
   internal
     strings
       strings.go
   main.go
```

We then use this module from our main application (let's call that `foo-go-app`), where the license scanning is being performed, but all of a sudden we're getting errors on `github.com/acme/foo-go-awesome/internal/strings` which we don't want.

The odd thing is that making it

```yml
ignored:
  go:
    - github.com/acme/foo-go-*/**/*
```

Does **not** ignore more of our internal module dependencies, but rather gives us **more** warnings (12 vs 2). Using that ignore all of a sudden picks up every single `github.com/acme/foo-go-*` module that we have a dependency on in `foo-go-app`. I can't quite shake the feeling that the ignore pattern isn't quite functioning as expected 😄

**Comment by jonabc** [comment] 2021-09-27 18:55
Ah got it!  thanks for the additional explanation.  I think this is functioning as expected, but that the expectations may not be clear 😆 .  The issue is that `**/` evaluates as you'd expect but the ending `*` is still expecting to match something past the `foo-go-*` identifier.

Put another way, the minimal match that I'd expect `github.com/acme/foo-go-*/**/*` to match is `github.com/acme/foo-go-*/*`, with the trailing `/*` being required to match the pattern. I would not expect this pattern to match `github.com/acme/foo-go-(car|boat|plane|train)` because they do not satisfy the trailing `/*`.

Using multiple patterns would help manage this scenario - does using this ignore configuration remove the extraneous warnings?

```yml
ignored:
  go:
    - github.com/acme/foo-go-*
    - github.com/acme/foo-go-*/**/*
```

**Comment by andreas-hakansson-ingka** [comment] 2021-09-27 19:11
@jonabc ah! Yes, that did work ❤️ I see now where my understanding was flawed

1. `github.com/acme/foo-go-*` will only match the root of any of our `foo-go-*` dependencies but not anything deeper
2. `github.com/acme/foo-go-*/**/*` will only match anything that is NOT in the root, i.e only things that are in one of more folder levels down

Yeah, that makes total sense now.

Thank you soooo much for your patience. Much love ❤️
