### ISSUE TITLE
mini_portile gem and its LICENSE.txt not being detected

### ISSUE THREAD

**Issue by pjmartorell** [github/licensed#353] opened 2021-04-09 15:09 UTC
Hi, when installing `mini_portile2` (2.5.0) and running `licensed cache -s bundler` is not detecting the license of the gem even it has it (https://github.com/flavorjones/mini_portile).

**Comment by jonabc** [comment] 2021-04-09 23:46
:wave: @pjmartorell I wasn't able to reproduce this with the following:
1. add `gem "mini_portile2", "2.5.0"` to [test/fixtures/bundler/Gemfile](https://github.com/github/licensed/blob/master/test/fixtures/bundler/Gemfile)
2. run `script/source-setup/bundler`
3. run `licensed list -c test/fixtures/command/bundler.yml` <- verify that mini_portile2 is listed
4. run `licensed cache -c test/fixtures/command/bundler.yml` <- verify that mini_portile2 data is cached at `test/fixtures/bundler/.licenses/bundler/mini_portile2.dep.yml`

If you're still having the problem can you verify that the gem is installed locally for the current bundler scope or gem installation path?  If you've verified the issue is persisting can you set up a small project repo or Gemfile that reproduces the problem?

Some other information that might be helpful are what versions of ruby and/or bundler you're using when you encounter the problem.

**Comment by pjmartorell** [comment] 2021-04-10 01:40
Hi @jonabc! thanks for the fast reply, I attach a [repo](https://github.com/pjmartorell/test) with a small project where I just:
- created a rails app with `rails new _6.0.3.5_ testapp` with ruby 2.7 
- added `licensed` gem and `.licensed.yml` config
- run `licensed cache -s bundler` and checked `mini_portile2` is not present even it's a dependency of a gem of the default/production group in the Gemfile.

- Ruby version 2.7, but I think it is not meaningful since it was happening the same with ruby 2.5 and 2.6
- Bundler 2.1.4

**Comment by jonabc** [comment] 2021-04-12 05:31
@pjmartorell thanks for the report and test repo, this is very helpful.  I'm still digging in, but the code for the bundler source is tricky because it's attempting to manipulate bundler, which in turn manipulates rubygems.  It's a bit of a mess that's compounded by trying to make the bundler source usable when run from the non-gem, standalone executable distributions.

From what I'm seeing locally, when running `licensed ...`, nokogiri is found from the system gem installation path but when running `bundle exec licensed ...` nokogiri is found from the local bundle gem installation path and finds mini_portile2.  I'm not sure why/how this is happening TBH but in the meantime, if you run `bundle exec licensed ...` it should correctly find all dependencies.

**Comment by pjmartorell** [comment] 2021-04-13 11:17
@jonabc thanks for the suggestion/workaround, it works. Similarly to what you pointed out, what I noticed is that:
- `licensed cache -s bundler` uses the latest bundler version installed in the system (in my case `2.2.16`) and updates the `bundler` license with version 2.2.16.
- `bundle exec licensed cache -s bundler` uses the version specified in the `BUNDLED WITH` of `Gemfile.lock` (in my case, `2.1.4`) and the bundler license is not updated (remains 2.1.4)

**Comment by jonabc** [comment] 2021-04-29 21:00
@pjmartorell I'm going to close this now as I believe this to be fixed with the 3.0.0 release today.  Please try out that version and reopen if you continue to see this bug 🙇

**Closed by jonabc** 2021-04-29 21:00 UTC
