### ISSUE TITLE
NPM/PIP - String does not have #dig method

### ISSUE THREAD

**Issue by timorkal** [github/licensed#449] opened 2022-02-06 17:29 UTC
Hello, I try to run basic cache command on a nodejs project and getting an error:

Using latest version: 3.4.3

licensed cache -c ./.licensed/licensed.yml

```
Caching dependency records for ***********
  npm
  * 0 npm dependencies
Traceback (most recent call last):
        36: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
        35: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
        34: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/exe/licensed:5:in `<top (required)>'
        33: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        32: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        31: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        30: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        29: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/cli.rb:18:in `cache'
        28: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/cli.rb:110:in `run'
        27: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:23:in `run'
        26: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/cache.rb:24:in `run_command'
        25: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:64:in `run_command'
        24: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:64:in `map'
        23: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:67:in `block in run_command'
        22: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:95:in `run_app'
        21: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:95:in `chdir'
        20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:98:in `block in run_app'
        19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:98:in `map'
        18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:101:in `block (2 levels) in run_app'
        17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/cache.rb:42:in `run_source'
        16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:136:in `run_source'
        15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/source.rb:67:in `dependencies'
        14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/source.rb:84:in `cached_dependencies'
        13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:31:in `enumerate_dependencies'
        12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:50:in `packages'
        11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `recursive_dependencies'
        10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `each'
         9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:75:in `block in recursive_dependencies'
         8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `recursive_dependencies'
         7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `each'
         6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:75:in `block in recursive_dependencies'
         5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `recursive_dependencies'
         4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:66:in `each'
         3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:67:in `block in recursive_dependencies'
         2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:143:in `missing_peer?'
         1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:150:in `peer_dependency'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/npm.rb:150:in `dig': String does not have #dig method (TypeError)
```

**Comment by timorkal** [comment] 2022-02-06 20:55
Also getting the same with pip:

`Traceback (most recent call last):
        21: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
        20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
        19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/exe/licensed:5:in `<top (required)>'
        18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/cli.rb:18:in `cache'
        13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/cli.rb:110:in `run'
        12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:23:in `run'
        11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/cache.rb:24:in `run_command'
        10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:64:in `run_command'
         9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:64:in `map'
         8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:67:in `block in run_command'
         7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:95:in `run_app'
         6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:95:in `chdir'
         5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:96:in `block in run_app'
         4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/commands/command.rb:96:in `select'
         3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/pip.rb:14:in `enabled?'
         2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/pip.rb:59:in `virtual_env_pip'
         1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/pip.rb:66:in `virtual_env_dir'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.4.3/lib/licensed/sources/pip.rb:66:in `dig': String does not have #dig method (TypeError)`

**Comment by villelahdenvuo** [comment] 2022-02-07 08:49
Duplicate of #448 could you share what dependencies you have (package.json, package-lock.json)?

**Comment by timorkal** [comment] 2022-02-07 08:55
sure.
**package.json**
```
{
  "name": "*********",
  "version": "*********",
  "private": true,
  "dependencies": {
    "@hookform/resolvers": "^0.1.0",
    "@tensorflow/tfjs": "^3.6.0",
    "@tensorflow/tfjs-vis": "^1.5.1",
    "axios": "^0.24.0",
    "date-fns": "^2.25.0",
    "history": "^4.7.2",
    "husky": "^1.1.3",
    "i18next": "^12.0.0",
    "i18next-browser-languagedetector": "^2.2.3",
    "i18next-xhr-backend": "^1.5.1",
    "js-file-download": "^0.4.12",
    "js-yaml": "^3.13.1",
    "lint-staged": "^8.0.4",
    "lodash": "^4.17.21",
    "lodash-checkit": "^2.1.0",
    "lodash-math": "0.0.7",
    "moment": "^2.23.0",
    "sass": "^1.45.1",
    "password-validator": "^4.1.1",
    "prettier": "^1.15.1",
    "rc-input-number": "^4.3.7",
    "react": "^16.13.1",
    "react-accessible-accordion": "^3.0.1",
    "react-bootstrap-modal": "^4.2.0",
    "react-contexify": "^4.1.1",
    "react-contextmenu": "^2.11.0",
    "react-copy-to-clipboard": "^5.0.2",
    "react-csv": "^1.1.2",
    "react-datepicker": "^4.3.0",
    "react-dom": "^16.6.1",
    "react-hook-form": "^6.7.1",
    "react-i18next": "^11.7.0",
    "react-json-editor-ajrm": "^2.5.9",
    "react-moment": "^0.8.4",
    "react-redux": "^7.2.0",
    "react-router": "^5.2.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "^3.4.1",
    "react-select": "^3.1.0",
    "react-table": "^6.10.0",
    "react-toastify": "^5.3.2",
    "react-tooltip": "^4.2.11",
    "recharts": "^1.4.2",
    "recompose": "^0.30.0",
    "redux": "^4.0.1",
    "redux-devtools-extension": "^2.13.5",
    "redux-form": "^8.3.6",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^0.83.0",
    "shortid": "^2.2.14",
    "toastr": "^2.1.4",
    "yup": "^0.29.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "lint": "eslint src --ext .js --ext .jsx",
    "lint:fix": "eslint src --ext .js --ext .jsx --fix"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "prettier": {
    "singleQuote": true
  },
  "lint-staged": {
    "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}": [
      "prettier --single-quote --write",
      "git add"
    ]
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "jest": {
    "transformIgnorePatterns": [
      "node_modules/(?!@ngrx|(?!deck.gl)|ng-dynamic)"
    ]
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "axios-mock-adapter": "^1.15.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.2.0",
    "eslint-config-react-app": "^3.0.5",
    "eslint-plugin-flowtype": "^2.50.3",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.0",
    "eslint-plugin-react": "^7.11.1",
    "moxios": "^0.4.0"
  }
}
```
package-lock.json is too long to attach

**Comment by jonabc** [comment] 2022-02-07 21:36
❤️ thanks for the assist @villelahdenvuo, and for the package.json for reproduction @timorkal !  I'll take a look at this (and https://github.com/github/licensed/issues/448) ASAP

**Comment by jonabc** [comment] 2022-02-07 23:26
@timorkal there are two issues causing problems here.

the problem with the npm source comes from an unexpected string value `"[Circular]"` which is set to a `peerDependencies` property key.

the problem in the pip source comes from an unexpected string value in the python property hash.  Please see the [docs](https://github.com/github/licensed/blob/master/docs/sources/pip.md#virtual_env_dir-required) for the expected configuration shape for the pip source.  Note that there is a small typo in there - there should be a space between the key `virtual_env_dir` and its value

I'm addressing all of the above in https://github.com/github/licensed/pull/450

**Comment by jonabc** [comment] 2022-02-08 03:27
closed by https://github.com/github/licensed/pull/450 and included in [3.4.4](https://github.com/github/licensed/releases/tag/3.4.4)

**Closed by jonabc** 2022-02-08 03:27 UTC

**Comment by rwwagner90** [comment] 2023-02-07 14:26
I'm still getting this error with 4.0.4

**Comment by rwwagner90** [comment] 2023-02-07 15:38
@jonabc sure thing, thanks for the quick reply! https://github.com/github/licensed/issues/625

**Comment by johnhunter** [comment] 2023-02-14 11:20
I'm seeing this on `3.9.1` with npm dependencies. It happens when upgrading npm itself from v6 to v9 (which includes a lockfile format migration to `lockfileVersion: 3` and config setting `legacy-peer-deps=true`)

**Comment by johnhunter** [comment] 2023-02-14 12:00
Odd one is that running `./licensed cache` on local (MacOS 12.6.3) succeeds but in CI (Ubuntu 20.04.5 LTS) it fails.

**Comment by johnhunter** [comment] 2023-05-25 15:00
The error I see with CI is

```
./licensed cache
Caching dependency records for XXXX
  npm
  * 0 npm dependencies
Traceback (most recent call last):
	41: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
	40: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
	39: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/exe/licensed:5:in `<top (required)>'
	38: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	37: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	36: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	35: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	34: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/cli.rb:18:in `cache'
	33: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/cli.rb:115:in `run'
	32: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:23:in `run'
	31: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/cache.rb:24:in `run_command'
	30: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:64:in `run_command'
	29: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:64:in `map'
	28: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:67:in `block in run_command'
	27: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/cache.rb:39:in `run_app'
	26: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/cache.rb:166:in `with_licensee_configuration'
	25: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/cache.rb:40:in `block in run_app'
	24: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:95:in `run_app'
	23: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:95:in `chdir'
	22: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:98:in `block in run_app'
	21: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:98:in `map'
	20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:101:in `block (2 levels) in run_app'
	19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/cache.rb:54:in `run_source'
	18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/commands/command.rb:136:in `run_source'
	17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/source.rb:72:in `dependencies'
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/source.rb:89:in `cached_dependencies'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:31:in `enumerate_dependencies'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:52:in `packages'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `each'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `each'
	 8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	 7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `each'
	 5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:77:in `block in recursive_dependencies'
	 4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `recursive_dependencies'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:68:in `each'
	 2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:74:in `block in recursive_dependencies'
	 1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:162:in `extract_version'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-3.9.1/lib/licensed/sources/npm.rb:162:in `dig': String does not have #dig method (TypeError)

Exited with code exit status 1

```

**Comment by johnhunter** [comment] 2023-06-02 15:33
Thanks for the response @jonabc.
Our issue seems to have been the result of running node@14 with a later npm version than the bundled one. We managed to resolve our blockers to upgrading node and the problem has resolved. We also updated to latest licensed without problems.
