### ISSUE TITLE
non-ASCII character causes crash

### ISSUE THREAD

**Issue by chrisd8088** [github/licensed#203] opened 2019-10-21 20:10 UTC
Running in a Linux Docker container, I've been running into the following -- if I can figure out what the input file is which is causing this, I'll add that info in a comment, but just capturing the output I've got so far now.

```
Traceback (most recent call last):
	46: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `<main>'
	45: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/bin/licensed:23:in `load'
	44: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/exe/licensed:5:in `<top (required)>'
	43: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	42: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	41: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	40: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	39: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/cli.rb:14:in `cache'
	38: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/cli.rb:83:in `run'
	37: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:22:in `run'
	36: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/reporter.rb:61:in `report_run'
	35: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:27:in `block in run'
	34: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:27:in `map'
	33: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:27:in `block (2 levels) in run'
	32: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:56:in `run_app'
	31: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:12:in `report_app'
	30: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/reporter.rb:83:in `report_app'
	29: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:14:in `block in report_app'
	28: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:57:in `block in run_app'
	27: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:57:in `chdir'
	26: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:64:in `block (2 levels) in run_app'
	25: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:64:in `map'
	24: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:64:in `block (3 levels) in run_app'
	23: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/cache.rb:26:in `run_source'
	22: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:81:in `run_source'
	21: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:26:in `report_source'
	20: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/reporter.rb:106:in `report_source'
	19: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:28:in `block in report_source'
	18: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:87:in `block in run_source'
	17: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:87:in `map'
	16: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:87:in `block (2 levels) in run_source'
	15: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:109:in `run_dependency'
	14: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:76:in `report_dependency'
	13: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/reporter.rb:128:in `report_dependency'
	12: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/reporters/cache_reporter.rb:77:in `block in report_dependency'
	11: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/command.rb:119:in `block in run_dependency'
	10: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/commands/cache.rb:49:in `evaluate_dependency'
	 9: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/dependency.rb:60:in `record'
	 8: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/dependency.rb:133:in `license_metadata'
	 7: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensed-2.5.0/lib/licensed/dependency.rb:68:in `license_key'
	 6: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/projects/project.rb:25:in `license'
	 5: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/projects/project.rb:156:in `licenses_without_copyright'
	 4: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/projects/project.rb:45:in `matched_files'
	 3: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/projects/project.rb:149:in `project_files'
	 2: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/projects/project.rb:77:in `readme_file'
	 1: from /__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/project_files/readme_file.rb:42:in `license_content'
/__enclose_io_memfs__/lib/ruby/gems/2.6.0/gems/licensee-9.11.0/lib/licensee/project_files/readme_file.rb:42:in `match': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by jonabc** [comment] 2019-10-21 20:13
@chrisd8088 :wave: closing as a duplicate of https://github.com/github/licensed/issues/51.  Please reopen if this is still broken after adding `ENV LANG` as described at  https://github.com/github/licensed/issues/51#issuecomment-397323671 🙇

**Closed by jonabc** 2019-10-21 20:13 UTC
Labels: bug

**Comment by chrisd8088** [comment] 2019-10-21 23:56
Thank you!  I discovered `export RUBYOPT="-KU -E utf-8:utf-8"` and that seems to work as well.
